language: go

addons:
  apt:
    packages:
      - docker-ce

services:
  - docker

before_install:
  - make clean

script:
  - make ci

after_success:
  - if [ -n "$TRAVIS_TAG" ]; then
    make login publish;
    fi
