---
version: '2.3'

services:
  base: &base
    volumes:
      - ./pkg:/go/src/github.com/MYOB-Technology/ops-kube-db-operator/pkg
      - $HOME/.kube:/root/.kube
      - $HOME/.aws:/root/.aws
    working_dir: /go/src/github.com/MYOB-Technology/ops-kube-db-operator
    build:
      context: .
      target: dep
    environment:
      KUBECONFIG: "/root/.kube/config"
      AWS_REGION: "ap-southeast-2"

  go:
    <<: *base
    entrypoint: go

  dep:
    <<: *base
    entrypoint: dep

  dep-dev:
    <<: *base
    volumes:
      - .:/go/src/github.com/MYOB-Technology/ops-kube-db-operator
    entrypoint: dep

  console:
    <<: *base
    command: sh

  gofmt:
    <<: *base
    entrypoint: gofmt

  goimports:
    <<: *base
    entrypoint: goimports

  gometalinter:
    <<: *base
    entrypoint: gometalinter

  gomplate:
    image: hairyhenderson/gomplate:latest
    working_dir: /postgres-exporter
    volumes:
      - "./yaml/postgres-exporter:/postgres-exporter"
    entrypoint: /gomplate

  kubectl:
    image: lachlanevenson/k8s-kubectl:v1.7.6
    working_dir: /postgres-exporter
    volumes:
      - "./yaml/postgres-exporter:/postgres-exporter"
      - "$HOME/.kube:/root/.kube"
