---
version: '2.3'
services:
  base: &base
    volumes:
      - .:/go/src/github.com/MYOB-Technology/ops-kube-db-operator
    working_dir: /go/src/github.com/MYOB-Technology/ops-kube-db-operator
    build: 
      context: .
      target: dep

  go:
    <<: *base
    entrypoint: go

  dep:
    <<: *base
    entrypoint: dep
