[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "~1.12.13"

[[constraint]]
  branch = "master"
  name = "github.com/lib/pq"

[[constraint]]
  name = "gopkg.in/DATA-DOG/go-sqlmock.v1"
  version = "1.3.0"

[[constraint]]
  name = "k8s.io/client-go"
  version = "~4.0.0"
