required = ["k8s.io/code-generator/cmd/client-gen", "k8s.io/code-generator/cmd/lister-gen", "k8s.io/code-generator/cmd/informer-gen"]
[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "~1.12.13"

[[constraint]]
  branch = "master"
  name = "github.com/lib/pq"

[[constraint]]
  name = "gopkg.in/DATA-DOG/go-sqlmock.v1"
  version = "1.3.0"

[[constraint]]
  branch = "master"
  name = "github.com/golang/glog"

[[constraint]]
  name = "k8s.io/code-generator"
  branch = "release-1.8"

[[override]]
  name = "k8s.io/gengo"
  revision = "75356185a9af8f0464efa792e2e9508d5b4be83c"

[[constraint]]
  name = "k8s.io/apiextensions-apiserver"
  branch = "release-1.8"

[[constraint]]
  name = "k8s.io/apimachinery"
  branch = "release-1.8"

[[constraint]]
  name = "k8s.io/client-go"
  branch = "release-5.0"

[[constraint]]
  name = "k8s.io/api"
  branch = "release-1.8"