db:
  name: my-special-db
  port: 5432
  host: localhost
  user: postgres
  password: password
  url: "postgresql://postgres:password@my-special-db.kube-system:5432/?sslmode=disable"

postgres:
  ## postgres image repository
  image: "postgres"
  imageTag: "9.6.5"

metrics:
  image: wrouesnel/postgres_exporter
  imageTag: v0.4.1
  imagePullPolicy: IfNotPresent
  port: 9187
  minInstances: 1
  datasource: "postgresql://postgres:password@my-special-db.kube-system:5432/?sslmode=disable"

## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
resources:
  requests:
    memory: 256Mi
    cpu: 100m