/*
MYOB 2017
All Rights Reserved
*/

// This file was automatically generated by lister-gen

package v1alpha1

// DBListerExpansion allows custom methods to be added to
// DBLister.
type DBListerExpansion interface{}

// DBNamespaceListerExpansion allows custom methods to be added to
// DBNamespaceLister.
type DBNamespaceListerExpansion interface{}
