/*
MYOB 2017
All Rights Reserved
*/

// This file was automatically generated by lister-gen

package v1alpha1

// PostgresDBListerExpansion allows custom methods to be added to
// PostgresDBLister.
type PostgresDBListerExpansion interface{}

// PostgresDBNamespaceListerExpansion allows custom methods to be added to
// PostgresDBNamespaceLister.
type PostgresDBNamespaceListerExpansion interface{}
