// Code generated by MockGen. DO NOT EDIT.
// Source: transformer.go

// Package mocks is a generated GoMock package.
package mocks

import (
	database "github.com/MYOB-Technology/ops-kube-db-operator/pkg/database"
	rds "github.com/aws/aws-sdk-go/service/rds"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockRDSTransformer is a mock of RDSTransformer interface
type MockRDSTransformer struct {
	ctrl     *gomock.Controller
	recorder *MockRDSTransformerMockRecorder
}

// MockRDSTransformerMockRecorder is the mock recorder for MockRDSTransformer
type MockRDSTransformerMockRecorder struct {
	mock *MockRDSTransformer
}

// NewMockRDSTransformer creates a new mock instance
func NewMockRDSTransformer(ctrl *gomock.Controller) *MockRDSTransformer {
	mock := &MockRDSTransformer{ctrl: ctrl}
	mock.recorder = &MockRDSTransformerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockRDSTransformer) EXPECT() *MockRDSTransformerMockRecorder {
	return m.recorder
}

// RDSToModel mocks base method
func (m *MockRDSTransformer) RDSToModel(db *rds.DBInstance) (*database.Database, error) {
	ret := m.ctrl.Call(m, "RDSToModel", db)
	ret0, _ := ret[0].(*database.Database)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RDSToModel indicates an expected call of RDSToModel
func (mr *MockRDSTransformerMockRecorder) RDSToModel(db interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RDSToModel", reflect.TypeOf((*MockRDSTransformer)(nil).RDSToModel), db)
}

// ModelToRDS mocks base method
func (m *MockRDSTransformer) ModelToRDS(req *database.Request, master *database.Credential) (*rds.CreateDBInstanceInput, error) {
	ret := m.ctrl.Call(m, "ModelToRDS", req, master)
	ret0, _ := ret[0].(*rds.CreateDBInstanceInput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ModelToRDS indicates an expected call of ModelToRDS
func (mr *MockRDSTransformerMockRecorder) ModelToRDS(req, master interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ModelToRDS", reflect.TypeOf((*MockRDSTransformer)(nil).ModelToRDS), req, master)
}
