/*
MYOB 2017
All Rights Reserved
*/

// This file was automatically generated by informer-gen

package v1alpha1

import (
	internalinterfaces "github.com/MYOB-Technology/ops-kube-db-operator/pkg/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// DBs returns a DBInformer.
	DBs() DBInformer
}

type version struct {
	internalinterfaces.SharedInformerFactory
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory) Interface {
	return &version{f}
}

// DBs returns a DBInformer.
func (v *version) DBs() DBInformer {
	return &dBInformer{factory: v.SharedInformerFactory}
}
