/*
MYOB 2017
All Rights Reserved
*/

// This file was automatically generated by informer-gen

package v1alpha1

import (
	internalinterfaces "github.com/MYOB-Technology/ops-kube-db-operator/pkg/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// PostgresDBs returns a PostgresDBInformer.
	PostgresDBs() PostgresDBInformer
}

type version struct {
	internalinterfaces.SharedInformerFactory
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory) Interface {
	return &version{f}
}

// PostgresDBs returns a PostgresDBInformer.
func (v *version) PostgresDBs() PostgresDBInformer {
	return &postgresDBInformer{factory: v.SharedInformerFactory}
}
