/*
MYOB 2017
All Rights Reserved
*/

// This file was automatically generated by informer-gen

package v1alpha1

import (
	time "time"

	postgresdb_v1alpha1 "github.com/MYOB-Technology/ops-kube-db-operator/pkg/apis/postgresdb/v1alpha1"
	versioned "github.com/MYOB-Technology/ops-kube-db-operator/pkg/client/clientset/versioned"
	internalinterfaces "github.com/MYOB-Technology/ops-kube-db-operator/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/MYOB-Technology/ops-kube-db-operator/pkg/client/listers/postgresdb/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// PostgresDBInformer provides access to a shared informer and lister for
// PostgresDBs.
type PostgresDBInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.PostgresDBLister
}

type postgresDBInformer struct {
	factory internalinterfaces.SharedInformerFactory
}

// NewPostgresDBInformer constructs a new informer for PostgresDB type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewPostgresDBInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				return client.PostgresdbV1alpha1().PostgresDBs(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				return client.PostgresdbV1alpha1().PostgresDBs(namespace).Watch(options)
			},
		},
		&postgresdb_v1alpha1.PostgresDB{},
		resyncPeriod,
		indexers,
	)
}

func defaultPostgresDBInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewPostgresDBInformer(client, v1.NamespaceAll, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc})
}

func (f *postgresDBInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&postgresdb_v1alpha1.PostgresDB{}, defaultPostgresDBInformer)
}

func (f *postgresDBInformer) Lister() v1alpha1.PostgresDBLister {
	return v1alpha1.NewPostgresDBLister(f.Informer().GetIndexer())
}
