---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: postgresdbs.myob.com
spec:
  group: myob.com
  version: v1alpha1
  names:
    kind: PostgresDB
    plural: postgresdbs
  scope: Namespaced
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgresdb-controller
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: postgresdb-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:postgresdb-controller
subjects:
- kind: ServiceAccount
  name: postgresdb-controller
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:postgresdb-controller
rules:
  - apiGroups:
      - "myob.com"
      - ""
    resources:
      - postgresdbs
      - namespaces
      - configmaps
      - secrets
    verbs:
      - get
      - list
      - watch
      - update
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgresdb-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: postgresdb-controller
    spec:
      serviceAccount: postgresdb-controller
      serviceAccountName: postgresdb-controller
      containers:
      - name: postgresdb-controller
        image: myobplatform/ops-kube-db-operator:latest
        env:
          - name: AWS_REGION
            value: "ap-southeast-2"
