---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: postgresdbs.myob.com
spec:
  group: myob.com
  version: v1alpha1
  names:
    kind: PostgresDB
    plural: postgresdbs
  scope: Namespaced
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresdb-controller
  namespace: kube-system
data:
  aws.security.group.id: sg-2610f740
  aws.subnet.group.name: test-rds-dataform
  aws.kms.key.arn: arn:aws:kms:ap-southeast-2:693429498512:key/62b05a23-2f82-467f-b61e-0e55531a3540
  aws.rds.postgres.default.port: "5432"
  aws.rds.postgres.default.multiaz: "true"
  aws.rds.postgres.default.kms.encryption: "true"
  aws.rds.postgres.default.instance.class: db2.t2.small
  aws.rds.postgres.default.backup.window: "14:00-15:00"
  aws.rds.postgres.default.maintenance.window: Sun:23:45-Mon:00:15
  aws.rds.postgres.default.storage.type: gp2
  aws.rds.postgres.default.storage.size: "5"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgresdb-controller
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: postgresdb-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:postgresdb-controller
subjects:
- kind: ServiceAccount
  name: postgresdb-controller
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:postgresdb-controller
rules:
  - apiGroups:
      - "myob.com"
      - ""
    resources:
      - postgresdbs
      - namespaces
      - configmaps
      - secrets
    verbs:
      - get
      - list
      - watch
      - update
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgresdb-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: postgresdb-controller
    spec:
      serviceAccount: postgresdb-controller
      serviceAccountName: postgresdb-controller
      containers:
      - name: postgresdb-controller
        image: myobplatform/ops-kube-db-operator:latest
        env:
          - name: AWS_REGION
            value: "ap-southeast-2"
